processing_model = {
    'None': lambda x: x,
    '- ': lambda x: [x.strip() for x in x.split('- ')[1:]],
    'to_int': lambda x: int(x.split(' ')[0]),
    'int_': lambda x: int(x),
    'float_': lambda x: float(x),
    '%_float': lambda x: float(x.split('%')[0]),
    '%_int': lambda x: int(x.split('%')[0]),
    'date_correction': lambda x: str(x.split(' ')[1] + '-' + month.get(x.split(' ')[0])),
    'to_float': lambda x: float(x.split(' ')[0]),
    'rsplit_str': lambda x: x.rsplit(' ', 1)[0],
    'to_bool': lambda x: False if x == 'Нет' else True,
    'int_list': lambda x: [int(x.strip()) for x in x.replace(' ГБ', '').split(',')],
    'flops': lambda x: float(x.replace('~', '').split(' ', 1)[0]),
    'str_to_list': lambda x: [x for x in x.split(',')]
}
main_model = {
    'title': ['title', 'None'],
    'brand': ['brand', 'None'],
    'Класс': ['category', 'None'],
    'Advantage': ['advantage', 'None'],
    'Disadvantage': ['disadvantage', 'None'],
    'Итоговая оценка': ['total_score', 'None'],
    'Дата выхода': ['announced', 'date_correction'],
    'Дата начала продаж': ['release_date', 'date_correction']
}
display_model = {
    'title': ['title', 'None'],
    'brand': ['brand', 'None'],
    'Дисплей': ['total_value', 'int_'],
    'Тип': ['display_type', 'None'],
    'Размер': ['d_size', 'to_float'],
    'Разрешение': ['resolution', 'rsplit_str'],
    'Частота обновления': ['refresh_rate', 'to_int'],
    'Реальная пиковая яркость (авто)': ['peak_brightness_test_auto', 'to_int'],
    'Макс. заявленная яркость': ['max_rated_brightness', 'to_int'],
    'Макс. заявленная яркость в HDR': ['max_rated_brightness_in_hdr', 'to_int'],
    'Плотность пикселей': ['ppi', 'to_int'],
    'Адаптивная частота обновления': ['adaptive_refresh_rate', 'to_bool'],
    'Поддержка HDR': ['hdr_support', 'None'],
    'Защита дисплея': ['screen_protection', 'None'],
    'ШИМ (PWM)': ['pwm', 'None'],
    'Соотношение экрана к корпусу': ['screen_to_body_ratio', '%_float'],
    'Контрастность': ['contrast', 'None'],
    'Время отклика': ['response_time', 'to_float'],
    'Особенности': ['display_features', '- '],
    'Цветовой охват sRGB': ['rgb_color_space', '%_float'],
    'Соотношение сторон': ['aspect_ratio', 'None']
}
performance_model = {
    'title': ['title', 'None'],
    'brand': ['brand', 'None'],
    'Производительность': ['total_value', 'int_'],
    'Чипсет': ['chipset', 'None'],
    'Макс. частота': ['max_clock', 'to_int'],
    'Объем ОЗУ': ['ram_size', 'int_list'],
    'Тип памяти': ['memory_type', 'None'],
    'Количество каналов': ['channels', 'int_'],
    'Объем накопителя': ['storage_size', 'int_list'],
    'Тип накопителя': ['storage_type', 'None'],
    'Карта памяти': ['memory_card', 'to_bool'],
    'CPU-ядер': ['cpu_cores', 'None'],
    'Архитектура': ['architecture', '- '],
    'Кэш L3': ['l3_cache', 'to_int'],
    'Размер транзистора': ['lithography_process', 'to_int'],
    'Графика': ['graphics', 'None'],
    'Частота GPU': ['gpu_clock', 'to_int'],
    'Игры': ['gaming', 'int_'],
    'Geekbench 5 (одноядерный)': ['geekbench_5_singlecore', 'int_'],
    'Geekbench 5 (многоядерный)': ['geekbench_5_multicore', 'int_'],
    'AnTuTu Benchmark 9': ['antutu_benchmark_9', 'int_'],
    '3DMark Wild Life Performance': ['3dmark_wild_life_performance', 'int_'],
    'PCMark 3.0': ['pcmark_3', 'int_'],
    'FLOPS': ['flops', 'flops'],
    'CPU': ['cpu', 'int_'],
    'GPU': ['gpu', 'int_'],
    'Memory': ['memory', 'int_'],
    'UX': ['ux', 'int_'],
    'Total score': ['total_score', 'int_'],
    'Пиковая температура корпуса': ['max_surface_temperature', 'None'],
    'Stability': ['stability', '%_int'],
    'Graphics test': ['graphics_test', 'to_int'],
    'Graphics score': ['graphics_score', 'int_'],
    'Web score': ['web_score', 'int_'],
    'Video editing': ['video_editing', 'int_'],
    'Photo editing': ['photo_editing', 'int_'],
    'Data manipulation': ['data_manipulation', 'int_'],
    'Writing score': ['writing_score', 'int_']
}
camera_model = {
    'title': ['title', 'None'],
    'brand': ['brand', 'None'],
    'Камера': ['total_value', 'int_'],
    'Матрица': ['matrix_main', 'to_float'],
    'Разрешение фото': ['image_resolution_main', 'None'],
    'Зум': ['zoom', 'None'],
    'Вспышка': ['flash', 'None'],
    'Стабилизация': ['stabilization', 'None'],
    'Количество объективов': ['lenses', 'None'],
    'Основной объектив': ['wide_main_lens', '- '],
    'Телефото объектив': ['telephoto_lens', '- '],
    'Сверхширокоугольный объектив': ['ultra_wide_lens', '- '],
    'Качество фото': ['photo_quality', 'int_'],
    'Качество видео': ['video_quality', 'int_'],
    'Итоговая оценка камеры': ['generic_camera_score', 'int_'],
    'Угол широкоугольного объектива': ['angle_of_widest_lens', 'None'],
    'Замедленная съемка': ['slow_motion', 'None'],
    'Запись 1080p видео': ['1080p_video_recording', 'None'],
    'Запись 4K видео': ['4k_video_recording', 'None'],
    'Запись 8K видео': ['8k_video_recording', 'None'],
    'Количество мегапикселей': ['megapixels_front', 'to_float'],
    'Разрешение фото -2-': ['image_resolution_front', 'None'],
    'Апертура': ['aperture_front', 'None'],
    'Фокусное расстояние': ['focal_length_front', 'to_float'],
    'Размер пикселя': ['pixel_size_front', 'to_float'],
    'Тип сенсора': ['sensor_type', 'None'],
    'Размер сенсора': ['sensor_size', 'None'],
    'Разрешение видео': ['video_resolution', 'None'],
    'Особенности -2-': ['camera_features', '- ']
}
energy_model = {
    'title': ['title', 'None'],
    'brand': ['brand', 'None'],
    'Батарея': ['total_value', 'int_'],
    'Объем': ['capacity', 'to_int'],
    'Макс. мощность зарядки': ['max_charge_power', 'to_float'],
    'Тип аккумулятора': ['battery_type', 'None'],
    'Съемный': ['replaceable', 'to_bool'],
    'Беспроводная зарядка': ['wireless_charging', 'None'],
    'Реверсивная зарядка': ['reverse_charging', 'None'],
    'Быстрая зарядка': ['fast_charging', 'None'],
    'Время полной зарядки': ['full_charging_time', 'None'],
    'Общая автономность': ['general_battery_life', 'None'],
    'Веб-серфинг': ['web_browsing', 'None'],
    'Просмотр видео': ['watching_video', 'None'],
    'Игры -2-': ['gaming_time', 'None'],
    'Режим ожидания': ['standby', 'None']
}
communication_model = {
    'title': ['title', 'None'],
    'brand': ['brand', 'None'],
    'Коммуникации': ['total_value', 'int_'],
    'NFC*': ['nfc', 'to_bool'],
    'Количество SIM*': ['number_of_sim', 'int_'],
    'Поддержка eSIM*': ['esim_support', 'to_bool'],
    'Гибридный слот': ['hybrid_slot', 'to_bool'],
    'Версия Wi-Fi': ['wifi_standard', 'None'],
    'Функции Wi-Fi': ['wifi_features', '- '],
    'Версия Bluetooth': ['bluetooth_version', 'None'],
    'Тип USB': ['usb_type', 'None'],
    'Версия USB': ['usb_version', 'float_'],
    'Функции USB': ['usb_features', '- '],
    'GPS': ['gps', '- '],
    'Инфракрасный порт': ['infrared_port', 'to_bool'],
    'Тип SIM': ['type_of_sim_card', 'None'],
    'Режим работы SIM': ['multi_sim_mode', 'None'],
    'Поддержка 5G': ['5g_support', 'to_bool']
}
physical_parameters_model = {
    'title': ['title', 'None'],
    'brand': ['brand', 'None'],
    'Высота': ['height', 'to_float'],
    'Ширина': ['width', 'to_float'],
    'Толщина': ['thickness', 'to_float'],
    'Вес': ['weight', 'to_float'],
    'Водонепроницаемость': ['waterproof', 'to_bool'],
    'Доступные цвета': ['colors', 'str_to_list'],
    'Максимальная громкость': ['max_loudness', 'to_float'],
    'Система охлаждения': ['advanced_cooling', 'None'],
    'Материал задней панели': ['rear_material', 'None'],
    'Материал рамки': ['frame_material', 'None'],
    'Сканер отпечатков пальцев': ['fingerprint_scanner', 'None'],
    'Операционная система': ['operating_system', 'None'],
    'Оболочка UI': ['rom', 'None'],
    'Размер системы из коробки': ['os_size', 'to_float'],
    'Динамики': ['speakers', 'None'],
    '3.5 мм аудио порт': ['headphone_audio_jack', 'to_bool'],
    'FM-Радио': ['fm_radio', 'to_bool'],
    'Dolby Atmos': ['dolby_atmos', 'to_bool'],
    'Уровень излучения SAR для головы': ['sar_head', 'to_float'],
    'Уровень излучения SAR для тела': ['sar_body', 'to_float'],
    'Сенсоры и датчики': ['sensors', '- '],
    'Зарядное устройство из коробки': ['charger_out_of_the_box', 'None']
}
month = {
    'Январь': '01',
    'Февраль': '02',
    'Март': '03',
    'Апрель': '04',
    'Май': '05',
    'Июнь': '06',
    'Июль': '07',
    'Август': '08',
    'Сентябрь': '09',
    'Октябрь': '10',
    'Ноябрь': '11',
    'Декабрь': '12'
}
