main_model = {
    'title': 'title',
    'brand': 'brand',
    'Класс': 'category',
    'Advantage': 'advantage',
    'Disadvantage': 'disadvantage',
    'Итоговая оценка': 'total_score',
    'Дата выхода': 'announced',
    'Дата начала продаж': 'release_date'

}
display_model = {
    'title': 'title',
    'brand': 'brand',
    'Дисплей': 'total_value',
    'Тип': 'display_type',
    'Размер': 'size',
    'Разрешение': 'resolution',
    'Частота обновления': 'refresh_rate',
    'Реальная пиковая яркость (авто)': 'peak_brightness_test_auto',
    'Макс. заявленная яркость': 'max_rated_brightness',
    'Макс. заявленная яркость в HDR': 'max_rated_brightness_in_hdr',
    'Плотность пикселей': 'ppi',
    'Адаптивная частота обновления': 'adaptive_refresh_rate',
    'Поддержка HDR': 'hdr_support',
    'Защита дисплея': 'screen_protection',
    'ШИМ (PWM)': 'pwm',
    'Соотношение экрана к корпусу': 'screen_to_body_ratio',
    'Контрастность': 'contrast',
    'Время отклика': 'response_time',
    'Особенности': 'display_features',
    'Цветовой охват sRGB': 'rgb_color_space',
    'Соотношение сторон': 'aspect_ratio'
}

performance_model = {
    'title': 'title',
    'brand': 'brand',
    'Производительность': 'total_value',
    'Чипсет': 'chipset',
    'Макс. частота': 'max_clock',
    'Объем ОЗУ': 'ram_size',
    'Тип памяти': 'memory_type',
    'Количество каналов': 'channels',
    'Объем накопителя': 'storage_size',
    'Тип накопителя': 'storage_type',
    'Карта памяти': 'memory_card',
    'CPU-ядер': 'cpu_cores',
    'Архитектура': 'architecture',
    'Кэш L3': 'l3_cache',
    'Размер транзистора': 'lithography_process',
    'Графика': 'graphics',
    'Частота GPU': 'gpu_clock',
    'Игры': 'gaming',
    'Geekbench 5 (одноядерный)': 'geekbench_5_singlecore',
    'Geekbench 5 (многоядерный)': 'geekbench_5_multicore',
    'AnTuTu Benchmark 9': 'antutu_benchmark_9',
    '3DMark Wild Life Performance': '3dmark_wild_life_performance',
    'PCMark 3.0': 'pcmark_3',
    'FLOPS': 'flops',
    'CPU': 'cpu',
    'GPU': 'gpu',
    'Memory': 'memory',
    'UX': 'ux',
    'Total score': 'total_score',
    'Пиковая температура корпуса': 'max_surface_temperature',
    'Stability': 'stability',
    'Graphics test': 'graphics_test',
    'Graphics score': 'graphics_score',
    'Web score': 'web_score',
    'Video editing': 'video_editing',
    'Photo editing': 'photo_editing',
    'Data manipulation': 'data_manipulation',
    'Writing score': 'writing_score'
}

camera_model = {
    'title': 'title',
    'brand': 'brand',
    'Камера': 'total_value',
    'Матрица': 'matrix_main',
    'Разрешение фото': 'image_resolution_main',
    'Зум': 'zoom',
    'Вспышка': 'flash',
    'Стабилизация': 'stabilization',
    'Количество объективов': 'lenses',
    'Основной объектив': 'wide_main_lens',
    'Телефото объектив': 'telephoto_lens',
    'Сверхширокоугольный объектив': 'ultra_wide_lens',
    'Качество фото': 'photo_quality',
    'Качество видео': 'video_quality',
    'Итоговая оценка камеры': 'generic_camera_score',
    'Угол широкоугольного объектива': 'angle_of_widest_lens',
    'Замедленная съемка': 'slow_motion',
    'Запись 1080p видео': '1080p_video_recording',
    'Запись 4K видео': '4k_video_recording',
    'Запись 8K видео': '8k_video_recording',
    'Количество мегапикселей': 'megapixels_front',
    'Разрешение фото -2-': 'image_resolution_front',
    'Апертура': 'aperture_front',
    'Фокусное расстояние': 'focal_length_front',
    'Размер пикселя': 'pixel_size_front',
    'Тип сенсора': 'sensor_type',
    'Размер сенсора': 'sensor_size',
    'Разрешение видео': 'video_resolution',
    'Особенности -2-': 'camera_features'
}

energy_model = {
    'title': 'title',
    'brand': 'brand',
    'Батарея': 'total_value',
    'Объем': 'capacity',
    'Макс. мощность зарядки': 'max_charge_power',
    'Тип аккумулятора': 'battery_type',
    'Съемный': 'replaceable',
    'Беспроводная зарядка': 'wireless_charging',
    'Реверсивная зарядка': 'reverse_charging',
    'Быстрая зарядка': 'fast_charging',
    'Время полной зарядки': 'full_charging_time',
    'Общая автономность': 'general_battery_life',
    'Веб-серфинг': 'web_browsing',
    'Просмотр видео': 'watching_video',
    'Игры -2-': 'gaming_time',
    'Режим ожидания': 'standby'
}

communication_model = {
    'title': 'title',
    'brand': 'brand',
    'Коммуникации': 'total_value',
    'NFC*': 'nfc',
    'Количество SIM*': 'number_of_sim',
    'Поддержка eSIM*': 'esim_support',
    'Гибридный слот': 'hybrid_slot',
    'Версия Wi-Fi': 'wifi_standard',
    'Функции Wi-Fi': 'wifi_features',
    'Версия Bluetooth': 'bluetooth_version',
    'Тип USB': 'usb_type',
    'Версия USB': 'usb_version',
    'Функции USB': 'usb_features',
    'GPS': 'gps',
    'Инфракрасный порт': 'infrared_port',
    'Тип SIM': 'type_of_sim_card',
    'Режим работы SIM': 'multi_sim_mode',
    'Поддержка 5G': '5g_support'
}

physical_parameters_model = {
    'title': 'title',
    'brand': 'brand',
    'Высота': 'height',
    'Ширина': 'width',
    'Толщина': 'thickness',
    'Вес': 'weight',
    'Водонепроницаемость': 'waterproof',
    'Доступные цвета': 'colors',
    'Максимальная громкость': 'max_loudness',
    'Система охлаждения': 'advanced_cooling',
    'Материал задней панели': 'rear_material',
    'Материал рамки': 'frame_material',
    'Сканер отпечатков пальцев': 'fingerprint_scanner',
    'Операционная система': 'operating_system',
    'Оболочка UI': 'rom',
    'Размер системы из коробки': 'os_size',
    'Динамики': 'speakers',
    '3.5 мм аудио порт': 'headphone_audio_jack',
    'FM-Радио': 'fm_radio',
    'Dolby Atmos': 'dolby_atmos',
    'Уровень излучения SAR для головы': 'sar_head',
    'Уровень излучения SAR для тела': 'sar_body',
    'Сенсоры и датчики': 'sensors',
    'Зарядное устройство из коробки': 'charger_out_of_the_box'
}

month = {
    'Январь': '01',
    'Февраль': '02',
    'Март': '03',
    'Апрель': '04',
    'Май': '05',
    'Июнь': '06',
    'Июль': '07',
    'Август': '08',
    'Сентябрь': '09',
    'Октябрь': '10',
    'Ноябрь': '11',
    'Декабрь': '12'
}
